### PR TITLE
cipher: impl AEADCipher chachapoly

### PR DESCRIPTION
**Pull request by stepheny**
Implement AEADCipher to invoke mbedtls_cipher_auth_encrypt and
mbedtls_cipher_auth_decrypt.
Implement _TestAEADCipher override cipher to accept ad, modified
test_encrypt_decrypt to accept encrypt and decrypt method passing
message with tag.

### CODE REVIEW

**Comment by stepheny** [comment]
Work in progress.
Is the change to encrypt/decrypt API acceptable?
Are the new classes' names ok?

If everything is ok, probably could be applied to aead aes ciphers.

**Comment by stepheny** [comment]
About the dual cipher_context usage, although it is comprehensible to use a Cipher object bidirectionally, but as a wrapper of `mbedtls_cipher_context_t` shouldn't it keep only one context instance? Isn't it higher level program logic's decision to use how many cipher contexts?

**Comment by Synss** [comment]
I have had a look at your patch and it looks very reasonable. Just let me play with it a little. I am sorry not to be very responsive right now but I will most likely merge your patch on the week end.

Regarding
> About the dual cipher_context usage, although it is comprehensible to use a Cipher object bidirectionally, but as a wrapper of mbedtls_cipher_context_t shouldn't it keep only one context instance? Isn't it higher level program logic's decision to use how many cipher contexts?

```cipher``` is one of the first things I have written for this library. Then, I could not find a way to encrypt and decrypt with a single ```mbedtls_cipher_context_t *```. My understanding to this day is that the call to ```mbedtls_cipher_setup()``` sets whether the context is for encryption or decryption and that this cannot be changed afterward. If you know a way to do this with a single context, that could reduce the number of lines of code, which is something I would appreciate. However note that I generally try to avoid keeping keys and passwords in Python as much as possible for security reasons. So this is another thing to take into account.

However, encrypting and decrypting within a single instance is mandated by [PEP 272](https://www.python.org/dev/peps/pep-0272/) and compliance with the various PEPs is important to me. I would not have designed the cipher package this way if it were up to me. I find calling a module-level factory function ```new()``` instead of just instantiating a cipher a little bit strange in Python. It nevertheless works and I take it as a piece of requirements.

**Comment by stepheny** [comment]
Thanks for the detailed explanation, now I knew where the problem was.
After a little digging into mbedtls' code and docs, it seems that it is designed to discriminate encrypt and decrypt contexts. Thus two contexts are necessary. Although it could be separated into a pair of mixins or some, but seems over-complicated.
You are right. Scenarios that only one way of a cipher is used should be rare.

**Comment by Synss** [comment]
Let me apologise once more for the delayed answer and the absolutely anticlimactic result: Your patch is perfect, thank you!

This closes #15.

**Pull request merged**
