### PR TITLE
pk: fix return value of curve_name_to_grp_id 

### PR DESCRIPTION
**Pull request by isombyt**
## The PR fulfills these requirements

- [ ] This change is a single feature in a single commit.
- [x] The commit message follows our commit guidelines.
- [x] The code formatting follows our coding guidelines.
- [ ] Tests have been added for the changes.
- [ ] Docs have been added / updated (docstrings *and* README).
- [ ] A one-liner has been added to the ChangeLog (for new features).

More details in [CONTRIBUTING](../CONTRIBUTING.md).

## I am submitting a …

- [x] Bug fix
- [ ] New feature
- [x] Tests update (new test vector, etc.)
- [ ] Docs update
- [ ] Other (please complete)

### CODE REVIEW

**Comment by Synss** [comment]
Hi @isombyt!

Nice catch! It indeed looks like the code was wrong there but some tests do not pass with your patch. Would you mind looking into it? I will investigate on my side as well.

**Comment by Synss** [comment]
I have just added a couple of patch on the dev branch (will merge them into master when they are green) to help with debugging. Your fix seems to break CURVE448 and CURVE25519. This is not so surprising. I am still working on it.

I can also confirm that, without your patch, `ECC.generate()` does not use the curve that was configured.

**Comment by isombyt** [comment]
Didn't expected this would break the unit tests. I'm looking into it.

**Comment by isombyt** [comment]
refer to upstream code. https://github.com/Mbed-TLS/mbedtls/blob/d65aeb37349ad1a50e0f6c9b694d4b5290d60e49/library/oid.c#L481
mbedtls have not OID definition for x25519 or x448, which means mbedtls does not have support export x25519 or x448 to DER/PEM.
In this case, maybe I should fix the unit test.

**Comment by isombyt** [comment]
update: still need to solve the export format problem. do not merge.

**Comment by Synss** [comment]
> update: still need to solve the export format problem. do not merge.

OK, looks great so far.

**Comment by isombyt** [comment]
should be good to go.

**Comment by Synss** [comment]
Thank you for your very clear contribution! I'll take care of the formatting errors.

**Comment by Synss** [comment]
merged in master

**Pull request closed without merging**
